apiVersion: v1
kind: Service
metadata:
  name: vuejs-front-service
spec:
  selector:
    app: vuejs-front
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-back-service
spec:
  selector:
    app: springboot-back
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
